### PR TITLE
Use OHHTTPStubs instead of aerogear-ios-httpstub

### LINKED ISSUE #45: Replace deprecated library aerogear-ios-httpstub
https://github.com/aerogear/aerogear-ios-httpstub has been deprecated. We could either switch to https://github.com/AliSoftware/OHHTTPStubs or check out https://github.com/kylef/Mockingjay.

### PR DESCRIPTION
**Pull request by tibr**
Closes #45 

Unfortunately OHHTTPStubs has not released a formal version in a while so I used `master`.

### CODE REVIEW

**Comment by bckr** [comment]
Wouldn't it be a bit saver to pin the dependency directly to the [commit](https://github.com/AliSoftware/OHHTTPStubs/commit/8f0f04866a2ffa1309527dd228151bba68b7fbae) we need instead of master?

**Comment by tibr** [comment]
The exact commit is referenced in the `Carthage.resolved` file: `github "AliSoftware/OHHTTPStubs" "8f0f04866a2ffa1309527dd228151bba68b7fbae"`

I think that when running `carthage bootstrap` that commit should be used automatically.

**Comment by bckr** [comment]
Ah, I see! :+1:

**Comment by tibr** [comment]
4e257bd1fe53ec8606ebcadeb5e65b83a8599311 now references the recently released version 3.1.11

**Comment by tibr** [comment]
52e71eb55aa16d3477b7040e6690880920b9b85e pins the exact commit just to be sure.

**Pull request merged**
