### PR TITLE
Let the user optionally configure the request authenticator

### LINKED ISSUE #42: Extract resource request authentication
Although using the HTTP `Authorization` header is probably the most common way of authenticating with a resource endpoint, there are many other options. Therefore, we should extract how a resource request is authenticated and make it configurable. Something like:

```swift
public protocol HeimdallResourceRequestAuthenticator {
  func authenticateResourceRequest(request: NSURLRequest, withAccessToken: OAuthAccessToken) -> NSURLRequest
}
```

### PR DESCRIPTION
**Pull request by tibr**
Fixes #42

### CODE REVIEW

**Comment by hffmnn** [comment]
> not add even more parameters to the initializer

we could add a new initializer and make the existing call it with a default value.

> give unit tests the chance to change the requestAuthenticator at any time

This is not an argument

For me the initial question of @bckr  still remains:
> Is it likely that the requestAuthenticator ever changes, once set?

**Comment by bckr** [comment]
My main argument against this change: Heimdall would lose immutability as one of its properties and I think that is a nice one to have. 

Another suggestion: Return a function capturing the requestAuthenticator?

**Comment by tibr** [comment]
I moved it into the initializer, should be good now @hffmnn @bckr

**Comment by bckr** [comment]
:+1:

**Pull request merged**
