### PR TITLE
Feature/read me updates

### PR DESCRIPTION
**Pull request by Gi-lo**
Updates readme:

* Add logo
* Add reference to Droid project

### CODE REVIEW

**Comment by DerLobi** [comment]
Wrong image

**Comment by tibr** [comment]
Nice, thanks a lot! @DerLobi we'll use the same image for both repositories because they are basically one project.

**Comment by Gi-lo** [comment]
@DerLobi You mean the color? I talked to @tibr and he suggested to use the green one.

**Comment by DerLobi** [comment]
Ah okay, yes. I have seen the logo in swift-orange

**Pull request merged**
